apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cloudkit-operator.yaml
- dex.yaml
- managed-cluster-config.yaml
- openshift-gitops.yaml
- root-app.yaml
- vault.yaml
- fulfillment-aap.yaml

# Apply some common sync options
patches:
- patch: |
    - op: add
      path: /spec/syncPolicy/syncOptions
      value:
      - CreateNamespace=true
    - op: add
      path: /spec/syncPolicy/automated/selfHeal
      value: true
  target:
    kind: Application
