apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/innabox/managed-cluster-apps.git
    path: apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
